import = ["/home/taha/.config/alacritty/themes/catppuccin-latte.toml"]
live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "SemiBold"

[font.glyph_offset]
y = 5

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
y = 6

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 1
decorations = "Buttonless"

[window.padding]
x = 10
y = 0
