import = ["/Users/taha/.config/alacritty/themes/catppuccin-latte.toml"]
live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "SemiBold"

[font.offset]
y = 6

[font.glyph_offset]
y = 3

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.95
blur = true
decorations = "Buttonless"
dynamic_padding = true
