# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules =
    [ "kvm-intel" "i2c-dev" "ddcci_backlight" "v4l2loopback" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.ddcci-driver
    config.boot.kernelPackages.v4l2loopback
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/481e23db-19f5-4db7-8776-bb99a2472ec9";
    fsType = "ext4";
  };

  fileSystems."/mnt/nvme" = {
    device = "/dev/disk/by-uuid/C22464E02464D8C5";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" "gid=100" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/249C-D3B0";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 8 * 1024;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
