git:
  paging:
    colorArg: always
    pager: delta --paging=never

os:
  edit: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S-#{window_index}').pipe --remote-send "<Cmd>lua require('scripts.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
  open: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S-#{window_index}').pipe --remote-send "<Cmd>lua require('scripts.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"

