windows:
  - name: network
    root: ~/
    layout: tiled
    panes:
      - ping 1.1.1.1 -i 0.5
      - ssh -N ubuntu@***** -L 2224:*****:1055
      - cd ~/ovpn
      - cd ~/Downloads/Xray-linux-arm64-v8a
  - name: gotop
    root: ~/
    layout: tiled
    panes:
      - gotop --color vice --rate 0.5s
